### ISSUE TITLE
Problem to setup the plugin

### ISSUE THREAD

**Issue by Moustiluigi** [MLG-Fortress/PrettySimpleShop#16]
This question has already been asked before, with no proper answer. The plugin doesn't seem to launch properly (with **Spigot 1.14.2**), do you have any idea why ?
Here are the logs when I try to do **/setprice**:

> [19:27:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'setprice' in plugin PrettySimpleShop v1.5 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

Thank you !

**Comment by Moustiluigi** [comment]
Edit, 12min afterward, setting EssentialX up makes it works. Thank you for your plugin,
also here's [a link](https://ci.ender.zone/job/EssentialsX/) in case somebody is in the same situation.

**Comment by RoboMWM** [comment]
yea, the plugin probably said something about no economy plugin being detected on server startup in the log.
