### ISSUE TITLE
Exception occurs when trying to buy

### ISSUE THREAD

**Issue by PipouWSH** [MLG-Fortress/PrettySimpleShop#17]
When trying to buy from a shop, it generates this in the server panel:

[PrettySimpleShop] Task #17 for PrettySimpleShop v1.5 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'buy' in plugin PrettySimpleShop v1.5
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:330) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at com.robomwm.prettysimpleshop.feature.BuyConversation$1.run(BuyConversation.java:84) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1005) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:953) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:798) [gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at jav
a.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.openBook(Lorg/bukkit/inventory/ItemStack;)V
at com.robomwm.prettysimpleshop.command.UnconfirmedTransaction.‹init›(BuyCommand.java:225) ~[?:?]
at com.robomwm.prettysimpleshop.command.BuyCommand.buyCommand(BuyCommand.java:137) ~[?:?]
at com.robomwm.prettysimpleshop.command.BuyCommand.onCommand(BuyCommand.java:99) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[gbinvl_spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
... 11 more

I host a Spiggot server under version 1.14, downloaded the latest file. 
I tried running Economy++ as economy pluggin.

**Comment by RoboMWM** [comment]
Try updating to spigot 1.14.2 or 1.14.3?
