### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by Bucky209** [MLG-Fortress/PrettySimpleShop#19]
The mod is working well but the console is constantly outputting this error

[13:11:05] [Server thread/WARN]: [PrettySimpleShop] Task #130 for PrettySimpleShop v1.6.0-50892ad generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(I)Lorg/bukkit/block/Block;
	at com.robomwm.prettysimpleshop.feature.ActionBarItemDetails.sendShopDetails(ActionBarItemDetails.java:72) ~[?:?]
	at com.robomwm.prettysimpleshop.feature.ActionBarItemDetails$1.run(ActionBarItemDetails.java:61) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

It sends this error 3 times per second. 
Picture attached is the console.
![shop](https://user-images.githubusercontent.com/53887651/62672583-a72af780-b9de-11e9-86a7-aa4ed7ce18cc.PNG)

How can I fix this? 
Thanks for your time

**Comment by RoboMWM** [comment]
I'm assuming you closed this due to being on an outdated spigot build?
