### ISSUE TITLE
Console Flooded

### ISSUE THREAD

**Issue by RoY7x** [MLG-Fortress/PrettySimpleShop#24]
So I'm very new to creating minecraft servers. So I don't know what might be causing this. I'm running now a paper server, after I was told it was better to use than spiggot. Ver 1.14.4

But anyway, after logging into my server, the server console keeps getting flooded with this, and I don't know what to do. If I'm reading right is this a conflict occuring with another plugin I have that is supposed to be creating backup zips of my worlds?

[10:25:32] [Server thread/WARN]: [PrettySimpleShop] Task #25 for PrettySimpleShop v1.6.0-50892ad generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(I)Lorg/bukkit/block/Block;
	at com.robomwm.prettysimpleshop.feature.ActionBarItemDetails.sendShopDetails(ActionBarItemDetails.java:72) ~[?:?]
	at com.robomwm.prettysimpleshop.feature.ActionBarItemDetails$1.run(ActionBarItemDetails.java:61) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[paper.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [paper.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [paper.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [paper.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [paper.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [paper.jar:git-Spigot-ea7e48b-368f4e9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by RoboMWM** [comment]
You're not using Paper here, this log is still using spigot.

That being said I don't see why it wouldn't work on spigot, so this is odd.

**Comment by RoY7x** [comment]
Huh... I kind of migrated what I had already setup with spigot and put paper in there. Making a server is complicated... I guess the Minecraft Server Soft app didn't do this properly...

I built a dedicated windows machine for my house so me and a few friends could play. With hopes of maybe having a few others later down the line. And this is the first time doing a Minecraft server so it's been a trip trying to even figure out how things all work. Permissions threw me for a loop the other day.

**Comment by RoboMWM** [comment]
However you're running it, it needs to run the `paperclip.jar` file instead of `spigot.jar`

**Comment by RoY7x** [comment]
but, I don't even have the spigot.jar file in my server directory I don't think, and MCSS points to running paper.jar at least is what I thought? Maybe I accidentally ran the old server quick on spigot.

**Comment by RoY7x** [comment]
My bad, MCSS was pointing to the wrong Jar it seems. It renamed my spigot.jar to paper.jar when it migrated, not telling me I needed to redownalod and then point it properly to paper-latest.jar. And now connecting to my game the error seems to have disappeared O_o

**Comment by RoboMWM** [comment]
Ya. Idk, maybe getTargetBlock was introduced in a later version of spigot or something - it's in the javadocs so I'm not sure why it's reporting that it doesn't exist.
