### ISSUE TITLE
Setprice command doesn't work for me

### ISSUE THREAD

**Issue by OnederfulCoder** [MLG-Fortress/PrettySimpleShop#29]
This is what I do:
I place the chest, I put in items, then I try to do /setprice 10 (price doesn't matter). 
This is the result: 
![2019-12-29_09 57 55](https://user-images.githubusercontent.com/54460578/71558493-0d61f680-2a22-11ea-8532-e7c298ca11be.png)

**Comment by OnederfulCoder** [comment]
Anyone help me please?

**Comment by RoboMWM** [comment]
Got the server log?

**Comment by OnederfulCoder** [comment]
no but I can attempt it again and show it. Do you want me to paste it here or use something like a screenshot?

**Comment by RoboMWM** [comment]
Paste. Use https://gist.github.com

**Comment by OnederfulCoder** [comment]
Here's a video of the issue (lemme know if I'm doing anything wrong.)
https://drive.google.com/file/d/1F6Yvqj0XEo9gnxBQzh94QLQqWsP_v9eH/view?usp=sharing
Here is latest.log: 
https://gist.github.com/OnederfulCoder/69ce3dbe996763315774f8fa6fae354d

**Comment by OnederfulCoder** [comment]
Wait, I found this in the log..
Could it be the issue? [WARNING] [PrettySimpleShop] Task #10 for PrettySimpleShop v1.4.2 generated an exception

**Comment by RoboMWM** [comment]
Yea, it's because you're using craftbukkit - I'll doublecheck what this plugin is doing regarding CB compatibility but I recommend using Paper in the meantime.

```
[WARNING] [PrettySimpleShop] Task #10 for PrettySimpleShop v1.4.2 generated an exception
java.lang.NoClassDefFoundError: net.md_5.bungee.api.chat.BaseComponent
at com.robomwm.prettysimpleshop.PrettySimpleShop$3.run(PrettySimpleShop.java:78) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit-1.13.2.jar:git-Bukkit-dfa7583]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [craftbukkit-1.13.2.jar:git-Bukkit-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:833) [craftbukkit-1.13.2.jar:git-Bukkit-dfa7583]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [craftbukkit-1.13.2.jar:git-Bukkit-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [craftbukkit-1.13.2.jar:git-Bukkit-dfa7583]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
```

**Comment by RoboMWM** [comment]
Hmm, is there any GitHub bot to remind me about open issues? Because there's no good way for GitHub to list all open issues in projects I follow...

**Comment by RoboMWM** [comment]
Since CB is deprecated by spigot (md_5) himself, I'll probably forego adding backcompat to this.

also I'm not sure why it'd use basecomponents here so I wonder if something else is going on.
